language: c
# Needed for libgcrypt20-dev
dist: trusty
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libusb-1.0-0-dev libgmp-dev libgcrypt20-dev
  - sudo apt-get install -y libelf-dev
script: make
